security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
            App\Entity\User: bcrypt
    providers:
        #in_memory: { memory: ~ }
        database_users:
            entity: { class: App\Entity\User, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            pattern: ^/

            form_login:
                check_path: security_login
                login_path: security_login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: user_profil

            logout:
                path: security_logout
                target: index

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: '^/user_profil', roles: ROLE_USER }
        - { path: '^/admin', roles: ROLE_ADMIN }